### ISSUE TITLE
Protobuf parsing failed onxruntime

### ISSUE THREAD

**Issue by Aivoice96** [hacksider/Deep-Live-Cam#748] opened 2024-10-28 18:09 UTC
I downloaded the last update from the deep live cam .. that was running before, but when I downloaded the update, when I stepped on the live button, this message appears and the image doesn't appear 

![image](https://github.com/user-attachments/assets/4effe969-2950-4972-8289-1414ab45fbd7)

I uninstalled the onxruntime and downloaded it more than once from the version but the same problem exists

**Comment by Aivoice96** [comment] 2024-10-28 18:35
up

**Comment by KRSHH** [comment] 2024-10-29 06:16
Duplicate of #697

**Closed by KRSHH** 2024-10-29 06:16 UTC
