### ISSUE TITLE
NSFW option doesn't appear on the application

### ISSUE THREAD

**Issue by Achraf80000** [hacksider/Deep-Live-Cam#355] opened 2024-08-16 01:40 UTC
![image](https://github.com/user-attachments/assets/6257c2f2-5500-481f-a2c1-dc8b77c23c1e)

**Comment by APD-01** [comment] 2024-08-16 03:34
edit the ui.py file in the modules directory:
Find these - 
#    nsfw_value = ctk.BooleanVar(value=modules.globals.nsfw)
#    nsfw_switch = ctk.CTkSwitch(root, text='NSFW', variable=nsfw_value, cursor='hand2', command=lambda: setattr(modules.globals, 'nsfw', nsfw_value.get()))
#    nsfw_switch.place(relx=0.6, rely=0.7)

Uncomment all three.

This should add the NSFW button back to the UI.
It worked for me Mac mini 2020 M1.

I've running now - will see how it goes - it didn't crash and die like it did before I reenabled the button, and turned it on.

Good Luck.

**Comment by Achraf80000** [comment] 2024-08-16 05:57
> edit the ui.py file in the modules directory: Find these -
> 
> # nsfw_value = ctk.BooleanVar(value=modules.globals.nsfw)
> # nsfw_switch = ctk.CTkSwitch(root, text='NSFW', variable=nsfw_value, cursor='hand2', command=lambda: setattr(modules.globals, 'nsfw', nsfw_value.get()))
> # nsfw_switch.place(relx=0.6, rely=0.7)
> Uncomment all three.
> 
> This should add the NSFW button back to the UI. It worked for me Mac mini 2020 M1.
> 
> I've running now - will see how it goes - it didn't crash and die like it did before I reenabled the button, and turned it on.
> 
> Good Luck.

Alright it worked, thanks for helping me out 
![image](https://github.com/user-attachments/assets/9458a68a-fc60-4eb8-814b-f3fbbd1e2f7f)

**Comment by vic4key** [comment] 2024-08-16 09:07
This function is working not very well in the main branch.
I will merge the fixed-PR in the experimental branch to the main branch soon.

PR @ https://github.com/hacksider/Deep-Live-Cam/pull/237

**Comment by spangurs** [comment] 2024-08-16 12:51
> edit the ui.py file in the modules directory: Find these -
> 
> # nsfw_value = ctk.BooleanVar(value=modules.globals.nsfw)
> # nsfw_switch = ctk.CTkSwitch(root, text='NSFW', variable=nsfw_value, cursor='hand2', command=lambda: setattr(modules.globals, 'nsfw', nsfw_value.get()))
> # nsfw_switch.place(relx=0.6, rely=0.7)
> Uncomment all three.
> 
> This should add the NSFW button back to the UI. It worked for me Mac mini 2020 M1.
> 
> I've running now - will see how it goes - it didn't crash and die like it did before I reenabled the button, and turned it on.
> 
> Good Luck.

whenever i uncomment the three lines it automatically crashes when i try to run the program but if i comment those three lines again it works, is there any fix?

**Comment by denrinm** [comment] 2024-08-16 16:16
@spangurs, it works for me.

I recommend using Python 3.10 or 3.11 and setting up a virtual environment. Once you have the environment ready, install all the dependencies listed in the requirements.txt file as described in the repository. After that, you should be able to uncomment those three lines without encountering any issues.

**Comment by spangurs** [comment] 2024-08-16 16:18
I mean i followed the exact instructions, followed mutahars video too and Everything works well but when uncommenting through either notepad or pycharm it just breaks until i comment them again. I got no clue what im doing, im not a coder or anything just wanna mess around haha

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by denrinm** [comment] 2024-08-16 16:25
@spangurs , could you please send your ui.py file? I'd be happy to take a look and see what changes you've made.

You also mentioned that the program crashes and doesn't run at all. If that's the case, it's probably that something might have been altered in the ui.py file. Please send it over so I can help you troubleshoot the issue.

**Comment by spangurs** [comment] 2024-08-16 16:30
@denrinm, Yeah sure I mean it works when i have the hashes in there and im pretty sure thats when its commented but once I remove them it opens the terminal then spews some words for a split seconds and close. Also I have no clue how to attach it because when i try to attach the file it says that they dont support the file type

**Comment by denrinm** [comment] 2024-08-16 16:33
@spangurs , upload it somewhere and give me the link .

**Comment by spangurs** [comment] 2024-08-16 16:35
@denrinm, I think this should work. https://file.io/LLAd903TN6WE

**Comment by denrinm** [comment] 2024-08-16 16:39
@spangurs , have you deleted it ? I can no longer download it ?

**Comment by denrinm** [comment] 2024-08-16 16:47
@spangurs spangurs, I tested it and found a minor typo that was causing the issue. It should work now. Please confirm: https://file.io/VGJOFvmIYls7

**Comment by spangurs** [comment] 2024-08-16 16:50
@denrinm 
![image](https://github.com/user-attachments/assets/b1da667a-bed3-406d-bc6b-3016f7ca749c)
there we go, thank you man. Not sure what you did but still thanks haha

**Comment by denrinm** [comment] 2024-08-16 16:53
@spangurs , it turns out there was an indentation issue, which is common if you haven't done much coding. When you mentioned that the software crashes without producing any logs, I suspected this might be the cause. Anyway, it's fixed now—enjoy!

**Comment by alexvndre0day** [comment] 2024-08-17 03:24
@denrinm it got deleted again, can u reupload? thanks

**Comment by ilyaphilin** [comment] 2024-08-19 14:52
@APD-01 Hi, I uncommented all three lines as you told, but now when I run "python run.py --execution-provider cuda" I get the following error:
![image](https://github.com/user-attachments/assets/6e49f67b-a2c7-4000-bc22-40250656cebe)
Could you assist please? Thank you in advance.

**Comment by katjaE2208** [comment] 2024-08-19 17:14
Hey, what means: Uncomment all three?
Find the entries
#    nsfw_value = ctk.BooleanVar(value=modules.globals.nsfw)
#    nsfw_switch = ctk.CTkSwitch(root, text='NSFW', variable=nsfw_value, cursor='hand2', command=lambda: setattr(modules.globals, 'nsfw', nsfw_value.get()))
#    nsfw_switch.place(relx=0.6, rely=0.7)

But what must I change? :) 

Like this?
#    nsfw_value = 
#    nsfw_switch = 
#    nsfw_switch.place

Thanks

**Comment by APD-01** [comment] 2024-08-19 23:08
@ ilyaphilin  I've not played with the CUDA version, I'm using an M1 Mac... but from the error message above looks like you've created an indentation error.
When you remove the "#" to uncomment the line, you need to replace it with a space - not just delete it.
E.g. 
#     <code here>
needs to become:
      <code here>
Not:
    <code Here>

---
It's just the way python works.  The number of spaces (rather the level of indentation), matters.

Good luck.

**Comment by vic4key** [comment] 2024-08-21 18:07
Feel free to re-open this issue if you’re still having trouble.

**Closed by vic4key** 2024-08-21 18:07 UTC

**Comment by nabel0** [comment] 2024-08-25 18:55
> Feel free to re-open this issue if you’re still having trouble.

It seems this PR was not propper merged into main imho.

If you look for example in the "ui.py" those lines are still uncommented:

https://github.com/hacksider/Deep-Live-Cam/blob/446487a70c60e66f8c088ee718cfa128d9d6505a/modules/ui.py#L93

**Comment by vic4key** [comment] 2024-08-26 05:31
Sorry, the NSFW function is currently unavailable. We have temporarily disabled it due to a violation of GitHub’s terms of service.
