### ISSUE TITLE
Blank Window when starting

### ISSUE THREAD

**Issue by aleksejmarkovic** [hacksider/Deep-Live-Cam#855] opened 2024-12-27 11:28 UTC
**Hello!**
I just downloaded and setup deep-live-cam, since the first time i tried to start running it, it always opens me a blank window.
My output when i run it also doesn't look bad or wrong, only thing suspicious is ''Frame processor face_enhancer not found''
Would appreciate any help!
![Image 27 12 24 at 12 25](https://github.com/user-attachments/assets/931b95ee-9df6-47c9-be58-d8738de06cdd)
![Image 27 12 24 at 12 22](https://github.com/user-attachments/assets/5c740d51-3b20-4247-9894-b8495721f1cd)

**Comment by KRSHH** [comment] 2024-12-27 14:06
Duplicate of #266

**Closed by KRSHH** 2024-12-27 14:06 UTC
