### ISSUE TITLE
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

### ISSUE THREAD

**Issue by WalkingwithAI** [hacksider/Deep-Live-Cam#651] opened 2024-09-27 17:42 UTC
Hello my friend, I get a wrong message when i run the run.py. I have created the conda venv and installed all dependencies. Looking forward your reply, thank you.
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Miniconda\envs\deeplivecam\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Miniconda\envs\deeplivecam\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "D:\Miniconda\envs\deeplivecam\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "D:\Miniconda\envs\deeplivecam\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by KRSHH** [comment] 2024-09-28 05:54
Duplicate of #643

**Closed by KRSHH** 2024-09-28 05:54 UTC
