### ISSUE TITLE
deep-live-cam  AttributeError: 'NoneType' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by inia123** [hacksider/Deep-Live-Cam#539] opened 2024-09-04 12:40 UTC
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\Python3.10.8\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "F:\github_ky\Deep-Live-Cam\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "F:\github_ky\Deep-Live-Cam\modules\ui.py", line 114, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview())
  File "F:\github_ky\Deep-Live-Cam\modules\ui.py", line 356, in webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "F:\github_ky\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 64, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "F:\github_ky\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 48, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "F:\github_ky\Deep-Live-Cam\venv\lib\site-packages\insightface\model_zoo\inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'reshape'

**Comment by AVGRadmin** [comment] 2024-09-04 12:51
Duplicate of https://github.com/hacksider/Deep-Live-Cam/issues/520.

**Comment by mrbingo1024** [comment] 2024-09-06 08:30
The same error. Has anyone resolved it?

**Comment by UltraSeeder** [comment] 2024-09-13 03:48
Change the source image. It works after that.

**Comment by robji15** [comment] 2024-10-26 16:43
搞定了，哈哈，原来是你导入的人脸图片路径不能包含中文

**Closed** 2024-10-31 19:01 UTC
