### ISSUE TITLE
ONNXruntimeerror

### ISSUE THREAD

**Issue by jaswindersinghdhami** [hacksider/Deep-Live-Cam#777] opened 2024-11-11 02:36 UTC
when selecting the camera the screen starts which is blank and this error onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/jazdhami/Documents/AI/deeplive/Deep-Live-Cam-main/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.

have tried both the models provided

**Comment by KRSHH** [comment] 2024-11-11 12:52
Duplicate of #697

**Closed by KRSHH** 2024-11-11 12:52 UTC
