### ISSUE TITLE
GUI isn't rendering properly

### ISSUE THREAD

**Issue by camtheperson** [hacksider/Deep-Live-Cam#223] opened 2024-08-12 16:14 UTC
![image](https://github.com/user-attachments/assets/bd058587-543b-4b21-9a58-c349af7c85f5)

Chip: Apple M3 Max
Platform: macOS 14.5 (23F79)

Anyone else run into this?

**Comment by kris-hansen** [comment] 2024-08-12 17:53
seeing the same behavior with an M3 Max on 14.6.1

**Comment by kris-hansen** [comment] 2024-08-12 18:18
Looks like the root cause is related to tcl-tk / Python version interaction. Resolved by installing tcl-tk via brew prior to installing the python version using pyenv and prepping the venv - this was a good hint: https://stackoverflow.com/questions/73056296/tkinter-on-mac-shows-up-as-a-black-screen

**Comment by AlexHayton** [comment] 2024-08-14 19:09
Same here

**Comment by farique** [comment] 2024-08-15 23:09
https://github.com/hacksider/Deep-Live-Cam/issues/38#issuecomment-2278970071

**Comment by dedeard** [comment] 2024-08-23 09:06
same here

**Closed** 2024-10-23 06:06 UTC
