### ISSUE TITLE
can run it but window is total blacnk

### ISSUE THREAD

**Issue by evanchai** [hacksider/Deep-Live-Cam#173] opened 2024-08-11 07:48 UTC
Environment: Python 3.10, MacBook Air, M2 2022, MacOS Sonoma
command: python3 run.py
<img width="1253" alt="Screenshot 2024-08-11 at 15 46 45" src="https://github.com/user-attachments/assets/271cb1bf-2ec1-417e-8a2e-9a28515c147c">

**Comment by axsaucedo** [comment] 2024-08-11 08:02
I can confirm same issue - additionally I get the following messages:

```
Frame processor face_enhancer not found
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
```

**Comment by evanchai** [comment] 2024-08-11 08:04
fixed this issue by 
brew install tcl-tk
pyenv install 3.10.4
according to previous solved issue

**Comment by axsaucedo** [comment] 2024-08-11 08:04
Seems this issue is duplicate of https://github.com/hacksider/Deep-Live-Cam/issues/119

**Closed** 2024-08-11 08:06 UTC
