### ISSUE TITLE
I really would thankful if you can help me get this application to face swap

### ISSUE THREAD

**Issue by szlateva** [hacksider/Deep-Live-Cam#744] opened 2024-10-27 08:29 UTC
After I run the program, the video live function doesn't work. This is what shows. I also tried to upload my own MP4 files in the target place and it would not let me drop the mp4 in the target area. This program looks amazing and I would be so grateful if you could help me to get it work one of the 2 ways. Thank you thank you!
![Screenshot 2024-10-27 012406](https://github.com/user-attachments/assets/5f05c40f-7b24-4473-b852-f11c954ed821)

**Comment by KRSHH** [comment] 2024-10-27 09:03
Duplicate of #697

**Closed by KRSHH** 2024-10-27 09:03 UTC

**Comment by earth77777** [comment] 2024-10-28 04:04
Thank you @KRSHH I am grateful.
I got the video(live) working. Thank you so much. Since the rate of frames a kind of slow, I want to try uploading pre-recorded video instead. Since that doesn't work, I will open a new issue request. Thank you again. I will give a donation on paypal once this is solved.Thank you so much

**Comment by KRSHH** [comment] 2024-10-28 04:12
> Thank you @KRSHH I am grateful. I got the video(live) working. Thank you so much. Since the rate of frames a kind of slow, I want to try uploading pre-recorded video instead. Since that doesn't work, I will open a new issue request. Thank you again. I will give a donation on paypal once this is solved.Thank you so much

Thanks
