### ISSUE TITLE
running on macos m3 chip just get a python window that is grey, nothing else

### ISSUE THREAD

**Issue by lasher169** [hacksider/Deep-Live-Cam#177] opened 2024-08-11 12:43 UTC
OS = macos 14.1 (23B2073)
chip = m3

screen is just grey when i run it.

I know the buttons exist as i can click on certain parts and it is asking me to search for a new face

<img width="602" alt="Screenshot 2024-08-11 at 10 42 48 pm" src="https://github.com/user-attachments/assets/37aa095a-1174-4b6a-b38b-5106f78a59f8">

I do get the following error in console 

DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.

python 3.10.0

**Comment by ITBeta** [comment] 2024-08-11 14:01
try to download the python 3.10 installer from python.org with using  python3.10 to create your venv. After that re-install requirements.txt with fresh pull from github. It work for me with my M1 macbook fix the glitch.

**Comment by storizzi** [comment] 2024-08-11 15:19
I'm using M3 too, seems to work fine for me. I had a shed-load of problems installing dependencies though, as always do with anything python related. I've created a mac installer in case these keep coming up (then I can uninstall / reinstall as needed) - https://github.com/storizzi/Deep-Live-Cam-Mac-Installer - see if any of the things being done there might be related to your issues

**Comment by danemacaulay** [comment] 2024-08-11 20:17
Duplicate of https://github.com/hacksider/Deep-Live-Cam/issues/119

**Closed** 2024-10-23 06:05 UTC
